config/routes.rb
Rails.application.routes.draw do
  root 'ships#index'
  devise_for :users

  resources :ships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ship.rb
class Ship < ApplicationRecord
	enum status: { arrived: 'arrived', queue: 'queue', processing: 'processing', processed: 'processed'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: %i[update]

  def index
    @arrived = Ship.arrived
    @queue   = Ship.queue
    @processed = Ship.processed.last(5)
  end

  def update
    @ship.update(status: params[:status])
    redirect_to ships_path
  end

  private

  def set_ship
    @ship = Ship.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShipDispatcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/ships/_arrived_ships.html.erb
<% if @arrived.present? %>
  <h1 class="text-center">Arrived Ships</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Serial No.</th>
          <th scope="col">Name</th>
          <th scope="col">status</th>
          <th scope="col">Origin</th>
          <th scope="col">Total Passengers</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <% @arrived.each_with_index do |ship, i| %>
        <tbody>
          <tr>
            <th scope="row"><%= i + 1 %></th>
            <td><%= ship.name %></td>
            <td><%= ship.status %></td>
            <td><%= ship.origin %></td>
            <td><%= ship.passengers %></td>
            <td><%= link_to "Send to queue", ship_path(ship, status: "queue"), method: :put %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
<% else %>
 <h1 class="text-center">No Ships arrived!</h1>
<% end %>

app/views/ships/_processed_ships.html.erb
<% if @processed.present? %>
  <h1 class="text-center">Processed Ships</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Serial No.</th>
        <th scope="col">Name</th>
        <th scope="col">status</th>
        <th scope="col">Origin</th>
        <th scope="col">Total Passengers</th>
      </tr>
    </thead>
    <% @processed.each_with_index do |ship, i| %>
      <tbody>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <td><%= ship.name %></td>
          <td><%= ship.status %></td>
          <td><%= ship.origin %></td>
          <td><%= ship.passengers %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% else %>
  <h1 class="text-center">No Ships in processed!</h1>
<% end %>

app/views/ships/_queue_ships.html.erb
<% if @queue.present? %>
  <h1 class="text-center">Queue Ships</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Serial No.</th>
        <th scope="col">Name</th>
        <th scope="col">status</th>
        <th scope="col">Origin</th>
        <th scope="col">Total Passengers</th>
        <!-- <th scope="col"></th> -->
      </tr>
    </thead>
    <% @queue.each_with_index do |ship, i| %>
      <tbody>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <td><%= ship.name %></td>
          <td><%= ship.status %></td>
          <td><%= ship.origin %></td>
          <td><%= ship.passengers %></td>
          <td><%#= link_to "Send to Processing", processing_ship_path(ship) %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% else %>
  <h1 class="text-center">No Ships in queue!</h1>
<% end %>

app/views/ships/index.html.erb
<%= render 'arrived_ships' %>
<%= render 'queue_ships' %>
<%= render 'processed_ships' %>